name: meet_dashes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  animations: ^2.0.11
  cloud_firestore: ^4.15.4  
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.5
  firebase_ui_auth: ^1.13.0
  firebase_ui_localizations: ^1.10.2
  firebase_ui_storage: ^2.0.3
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  json_annotation: ^4.8.1
  pretty_qr_code: ^3.2.1
  provider: ^6.1.1
  qr_code_scanner: ^1.0.1
  rive: ^0.12.4
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/rive/dash.riv
    - assets/images/
